### ISSUE TITLE
Add plugin configurations 

### ISSUE THREAD

**Issue by TiagoJacobs** [bigbluebutton/bigbluebutton-html-plugin-sdk#55]
I am writing to share insights and propose enhancements following our recent demonstration at the BigBlueButton Summit 2023. We successfully showcased a prototype that integrates the plugin SDK to support hybrid classrooms. This prototype involved loading a plugin into BBB and establishing a WebSocket connection to an external service using a hardcoded address.

Post-demonstration discussions highlighted the need for advancements in the professional application of this prototype for production environments. A key area of improvement identified is the ability to specify configurable parameters for each plugin, particularly concerning the server endpoints that the plugins interact with.

To address this, I suggest implementing a feature in the plugin architecture that allows for customizable configurations accessible via the plugin's JavaScript API. This enhancement would enable users to define specific settings for each plugin, enhancing the flexibility and adaptability of our system in diverse use cases.

Below is an illustrative example of how such configurations might be structured:

```yml
plugins:
  - name: SampleActionButtonDropdownPlugin
    url: http://127.0.0.1:4701/static/SampleActionButtonDropdownPlugin.js
    configuration:
      serverUrl: http://some-server
      otherConfig: [Additional Configuration Details]
```
